### ISSUE TITLE
Missing upos

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Portuguese-GSD#23]
we have several cases of empty features in upos:

```
% awk '$6 ~ /_/ && $4 !~ /PUNCT/ {print $4}' *.conllu | sort | uniq -c | sort -n -r
  56311 NOUN
  51935 ADP
  32920 PROPN
  27579 VERB
  26306 DET
  21914 _
  15111 ADJ
  10986 CCONJ
   8286 ADV
   7389 PRON
   7363 AUX
   1009 SYM
    750 PART
    534 X
      2 SCONJ
```

**Comment by wellington36** [comment]
> All these empty (underscore) UPOS tags are in multiword tokens, so it is OK. **MWTs must have empty UPOS** according to [the guidelines](https://universaldependencies.org/format.html#words-tokens-and-empty-nodes):
> 
> > They have a FORM value – the string that occurs in the sentence – but have an underscore in all the remaining fields except MISC
> 
> Empty UPOS in words would not be allowed by [the validator](https://github.com/UniversalDependencies/tools/blob/master/validate.py).
> 
> If you want to search in words only (excluding MWTs), you can use e.g. [Udapi](https://github.com/udapi/udapi-python) and `cat *.conllu | udapy -TM util.Mark node='node.upos=="_"' | less -R` (which shows no matches in case of UD_Portuguese-GSD).

@martinpopel, thanks for your comment. I corrected the initial comment.

**Comment by martinpopel** [comment]
Oh, I see. I haven't read the `awk` command carefully. I still think the MWTs should be filtered out from the query as these are OK (either by `$1 !~ /#|-/` or `$4 !~ /PUNCT|_/`). 
FEATS annotation is optional in UD in general. There used to be rules/suggestions that every VERB has `VerbForm`, every NUM has `NumType` and every DET and PRON has `PronType`, but I cannot find these rules in the official UD documentation now. They are still included in [ud.MarkBugs](https://github.com/udapi/udapi-python/blob/master/udapi/block/ud/markbugs.py). Of course, there may be additional language-specific rules requiring FEATS also for other parts of speech.

BTW: regarding general validation errors, the official validator gives me many [L3](https://universaldependencies.org/validation-rules.html#level-3-universal-guidelines) and L5 errors, when applied on the files in the master and dev branch, although the [validation report](http://quest.ms.mff.cuni.cz/udvalidator/cgi-bin/unidep/validation-report.pl) currently does not show any errors for UD_Portuguese-GSD.

The Udapi validation `git checkout dev; cat *.conllu | udapy -TMA ud.MarkBugs | less -R` also shows many errors (with `no-VerbForm` and `no-PronType` being the most frequent ones):
```
bugs = ud.MarkBugs Error Overview:
           aux-child          1
        punct-deprel          4
   appos-rightheaded          6
         punct-child          7
          multi-subj         14
             cc-upos         37
            cop-upos         39
           mark-upos         40
           multi-obj         45
          mark-child         66
   punct-nonproj-gap         77
       punct-nonproj        201
         punct-alpha        250
            det-upos        286
     cop-many-lemmas        414
          case-child        456
         no-VerbForm      27579
         no-PronType      33697
               TOTAL      63219
```

**Comment by wellington36** [comment]
I didn't know this ```git checkout dev; cat *.conllu | udapy -TMA ud.MarkBugs | less -R``` of Udapi, interesting. I really need run this in https://github.com/UniversalDependencies/UD_Portuguese-Bosque.

**Comment by martinpopel** [comment]
> I'm not sure what in the linked report you are looking at, but there are plenty of errors

Oh, I see. I was in a hurry and perhaps confused UD_Portuguese-PUD with UD_Portuguese-GSD (unfortunately, [not for the first time](https://github.com/UniversalDependencies/UD_Portuguese-GSD/issues/15#issuecomment-622473319)).

So while I agree that FEATS are useful and it would be nice to annotate them in GSD in the same way as in Bosque, it seems that fixing the errors reported by the validator should have a higher priority.

**Comment by wellington36** [comment]
> So while I agree that FEATS are useful and it would be nice to annotate them in GSD in the same way as in Bosque, it seems that fixing the errors reported by the validator should have a higher priority.

Really, knowing the amount of errors, I agree to work on these cases soon.

**Comment by arademaker** [comment]
> Portuguese-GSD is a legacy treebank, meaning that it was allowed to release it even with these errors, but it is not a valid treebank. Spoiler: it is likely that the legacy status will not be granted forever. There are proposals to limit it to a certain number of years after the validator started reporting the error.

Yes @martinpopel, I also don't want to keep GSD as a legacy treebank. We are trying to put some time here to make it more compatible with the https://github.com/UniversalDependencies/UD_Portuguese-Bosque. I also agree that errors reported by the [validate.py](https://github.com/UniversalDependencies/tools/blob/master/validate.py) are the most important ones. BTW, how do you compare `ud.MarkBugs` block with the validate.py script?

**Comment by martinpopel** [comment]
>  how do you compare ud.MarkBugs block with the validate.py script?

They have different goals but they should be complementary.

All UD treebanks (except for the legacy ones) must pass `validate.py`.
In `ud.MarkBugs`, I tried to focus on phenomena which are frequently annotation errors, but there may be rare exceptions which are OK, or rather questionable but not explicitly forbidden by the UD rules.
`ud.MarkBugs` intentionally does not check low-level CoNLL-U format requirements - I did not want to duplicate the code of `validate.py`. Also the whole Udapi tries to be very forgiving (and fast) when reading CoNLL-U (because many of the problems can be fixed using Udapi) - it fails only on unrecoverable errors such as cycles in the basic dependencies.

I wrote ud.MarkBugs in 2017 and there are [almost no updates since then](https://github.com/udapi/udapi-python/commits/master/udapi/block/ud/markbugs.py). In 2017, I think there was no overlap, but [meanwhile]((https://github.com/UniversalDependencies/tools/commits/master/validate.py)) some of the checks were included in `validate.py` as well.

We can extend `ud.MarkBugs` with new checks if needed. It is [being used](https://github.com/UniversalDependencies/tools/blob/master/evaluate_treebank.pl) for computing the stars indicating treebank quality, but that't just an informal visual aid (mostly for users who want to select the best treebank for a given language).
