### ISSUE TITLE
validation error: L5 Morpho aux-lemma and cop-lemma

### ISSUE THREAD

**Issue by wellington36** [UniversalDependencies/UD_Portuguese-GSD#29]
in folder https://github.com/UniversalDependencies/UD_Portuguese-GSD/tree/workbench/reports we have aux-lemma errors, they can be found using:

```
grep 'L5 Morpho aux-lemma' *.report | wc -l
134
```

**Comment by arademaker** [comment]
correto, este erro acusa que verbos não registrados como AUX para a Português estão sendo usados como AUX. No 9ebedf5, no entanto, eu mostro como corrigir estes casos irá modificar substancialmente as árvores sintáticas. 

@leoalenc `termina por viver`  concorda com `xcomp(viver, termina)` ?

**Comment by arademaker** [comment]
Solving these two errors would improve a lot the situation:

```
% grep -h --color -o -E "(\[L[0-9][^]]+\])" reports/*.report  | sort | uniq -c | sort -nr
 530 [L5 Morpho aux-lemma]
 515 [L3 Syntax leaf-mark-case]
 279 [L3 Syntax rel-upos-det]
 193 [L3 Syntax punct-is-nonproj]
 151 [L5 Syntax cop-lemma]
  80 [L3 Syntax rel-upos-case]
  79 [L3 Syntax punct-causes-nonproj]
  59 [L3 Syntax rel-upos-advmod]
  51 [L3 Syntax rel-upos-mark]
  39 [L3 Syntax rel-upos-cop]
  37 [L3 Syntax rel-upos-nummod]
  26 [L3 Syntax rel-upos-cc]
  26 [L3 Syntax rel-upos-aux]
  14 [L3 Syntax too-many-subjects]
   5 [L3 Syntax right-to-left-appos]
   4 [L3 Syntax rel-upos-expl]
   3 [L3 Syntax upos-rel-punct]
   2 [L3 Syntax leaf-aux-cop]
   1 [L3 Syntax leaf-cc]
```

**Comment by AngledLuffa** [comment]
For this one there's a class of sentences which would be a lot easier to automatically rewrite.  The ones that go `AUX a VERB` for example.  It looks like the pattern you used in "passam a fazar" was to make the first verb the root and the second verb link with an xcomp.  One issue I would have would be that I would not know what features to put on the verb we change to VERB.  Then again, there are many VERBs in the treebank without features, so this would just be a few more without those labels.

In the case where the second verb is not the root, though, what dependency should the first verb have?  Should it just use the dependency that was previously on the second verb?

Minor point, the `xpos` and `upos` are almost always the same except for punctuation in this treebank, and it appears your initial sample change did not keep the `xpos` field.

**Comment by AngledLuffa** [comment]
Also, what about ADP vs SCONJ?  The word `a` had its POS changed.  Would that be a universal change?

**Comment by arademaker** [comment]
The last four commits are related to this issue. We still have 487+145 = 632 cases to close this issue. 

```
% grep -h --color -o -E "(\[L[0-9][^]]+\])" *.report  | sort | uniq -c | sort -nr
 503 [L3 Syntax leaf-mark-case]
 487 [L5 Morpho aux-lemma]
 276 [L3 Syntax rel-upos-det]
 159 [L3 Syntax punct-is-nonproj]
 145 [L5 Syntax cop-lemma]
  80 [L3 Syntax rel-upos-case]
  79 [L3 Syntax punct-causes-nonproj]
  59 [L3 Syntax rel-upos-advmod]
  51 [L3 Syntax rel-upos-mark]
  39 [L3 Syntax rel-upos-cop]
  37 [L3 Syntax rel-upos-nummod]
  26 [L3 Syntax rel-upos-aux]
  25 [L3 Syntax rel-upos-cc]
  14 [L3 Syntax too-many-subjects]
   5 [L3 Syntax right-to-left-appos]
   4 [L3 Syntax rel-upos-expl]
   3 [L3 Syntax upos-rel-punct]
   2 [L3 Syntax leaf-aux-cop]
```

**Comment by AngledLuffa** [comment]
Happy to continue to help, but I need some guidance on how.  For example, the punct dependencies should theoretically be easy to fix, but I would want to make sure I'm doing the right thing.

Here is a punct dependency the validation script doesn't like:

```
# sent_id = dev-s388
# text = Edição: Fábio Massalli / / matéria atualizada às 17h40 do dia 5 de dezembro para correção da informação de que a Rede de Gestão Integrada de Ciência, Tecnologia e Inovação e a Rede Ipê eram sinônimos.
1       Edição  edição  NOUN    NOUN    _       0       root    _       SpaceAfter=No
2       :       :       PUNCT   .       _       7       punct   _       _
3       Fábio   _       PROPN   PNOUN   _       1       appos   _       _
4       Massalli        _       PROPN   PNOUN   _       3       flat    _       _
5       /       /       PUNCT   .       _       7       punct   _       _
6       /       /       PUNCT   .       _       7       punct   _       _
7       matéria matéria NOUN    NOUN    _       1       conj    _       _
8       atualizada      atualizar       VERB    VERB    _       7       acl     _       _
```

Node 2 is a problem because of the crossing dependencies `(7, 2)` and `(1, 3)`.  My guess would be to make 2 depend on 1 instead...  does that sound right?  I could possibly generalize that to say that if the punctuation's arc crosses another arc `(gov, dep)`, we replace it with a new arc `(gov, punct)`.

Does that sound good?  I can mock it up in a branch and you could tell me if it's on the right track.

While we're here, I wonder if `//` should originally have been kept as a single token with no space in that sentence.  Not a big deal.

**Comment by AngledLuffa** [comment]
For example:

https://github.com/UniversalDependencies/UD_Portuguese-GSD/commit/9ed4e1ec98641d179f9fec6a85c7af59c989ab00

This only looks at arcs going in one direction - I can expand it to cover a wider range of arcs if this looks mostly correct.

**Comment by arademaker** [comment]
@AngledLuffa in the current stage, I see

```
grep -h --color -o -E "(\[L[0-9][^]]+\])" *.report  | sort | uniq -c | sort -nr
 501 [L3 Syntax leaf-mark-case]
 477 [L5 Morpho aux-lemma]
 276 [L3 Syntax rel-upos-det]
 158 [L3 Syntax punct-is-nonproj]
 145 [L5 Syntax cop-lemma]
  80 [L3 Syntax rel-upos-case]
  79 [L3 Syntax punct-causes-nonproj]
  59 [L3 Syntax rel-upos-advmod]
  51 [L3 Syntax rel-upos-mark]
  39 [L3 Syntax rel-upos-cop]
  37 [L3 Syntax rel-upos-nummod]
  26 [L3 Syntax rel-upos-aux]
  25 [L3 Syntax rel-upos-cc]
  14 [L3 Syntax too-many-subjects]
   5 [L3 Syntax right-to-left-appos]
   4 [L3 Syntax rel-upos-expl]
   3 [L3 Syntax upos-rel-punct]
   2 [L3 Syntax leaf-aux-cop]
```

This issue is about fixing the 477+145 errors related to aux-lemma and cop-lemma. We can have another issue with the punct-causes-nonproj, but these are only 79 cases. So let me continue to fix the errors in this issue. I hope to finish in one week to discuss whatever we can automate again.

**Comment by AngledLuffa** [comment]
Where are we with this?  I believe the data freeze has happened, but
perhaps we can ask nicely and show some recent work to get an extension on
this dataset being b&

Also, if there's any way I can help with some automated updates, please let
me know.  I would have expected the punct updates to be useful at some
point, either a few weeks ago or as part of an ongoing update

**Comment by arademaker** [comment]
Hi @AngledLuffa, thank you so much for your offer. As you can see from the commits, I have been working to fix all issues. Unfortunately, I told @dan-zeman that I would not be able to complete the fixes before the next data freezing.

(actually I am not sure if we are already in the data freeze stage, I didn't get any notification).

I need to finish some urgent tasks until the end of this month, next I return to this issue. I believe for this issue here work need to be manual. At least, I didn't recognize any pattern so far.

Later we can discuss the issue with non-projective punctuation, this surely should be automated. Does it sounds good to you?

**Comment by arademaker** [comment]
Related to #36, closed.
